from tkinter import *
root = Tk()
root.geometry('500x500')
l_name = Label(root, text='Name: ')
e_name = Entry(root, width=20)
l_family = Label(root, text='Family: ')
e_family = Entry(root)
l_age = Label(root, text='Age: ')
# s_age = Spinbox(root, from_=1, to=5, state='readonly', wrap=True)
s_age = Spinbox(root, from_=1, to=5, state='readonly')
l_gender=Label(root, text="Gender: ")
s=IntVar()
r1 = Radiobutton(root, text='Female', variable=s, value=1)
r2 = Radiobutton(root, text='Male', variable=s, value=2)
l_name.grid(row=1, column=1, padx=10, sticky='w', pady=5)
e_name.grid(row=1, column=2, columnspan=2, padx=10, sticky='ew')
l_family.grid(row=2, column=1, padx=10, sticky='w', pady=5)
e_family.grid(row=2, column=2, columnspan=2, padx=10, sticky='ew')
l_age.grid(row=3, column=1, padx=10, sticky='w', pady=5)
s_age.grid(row=3, column=2, columnspan=2, padx=10, sticky='ew')
l_gender.grid(row=4, column=1, padx=10, sticky='w', pady=5)
r1.grid(row=4, column=2, padx=10, sticky='ew')
r2.grid(row=4, column=3, padx=10, sticky='ew')
mainloop()