from tkinter import *

root = Tk()
root.geometry('600x400')

btn9 = Button(root,text=9, padx=10, pady=10)
btn8 = Button(root,text=8, padx=10, pady=10)
btn7 = Button(root,text=7, padx=10, pady=10)
btn6 = Button(root,text=6, padx=10, pady=10)
btn5 = Button(root,text=5, padx=10, pady=10)
btn4 = Button(root,text=4, padx=10, pady=10)
btn3 = Button(root,text=3, padx=10, pady=10)
btn2 = Button(root,text=2, padx=10, pady=10)
btn1 = Button(root,text=1, padx=10, pady=10)
btn0 = Button(root, text='0', padx=10, pady=10)
btn000 = Button(root,text='000', padx=10, pady=10)
btnm = Button(root,text='-', padx=10, pady=10)
btnz = Button(root,text='*', padx=10, pady=10)
btn = Button(root,text='/', padx=10, pady=10)
btns = Button(root,text='=', padx=10, pady=10)
btnb = Button(root,text='+', padx=10, pady=10)
btnc = Button(root,text='c', padx=10, pady=10)
entry = Entry(root)

# ==========================
entry.grid(row=0, column=1, columnspan=5, sticky='nsew')
btnc.grid(row=1, column=5, sticky='nsew')
btnb.grid(row=1, column=4, rowspan=2, sticky='nsew')
btns.grid(row=4, column=4, columnspan=2, sticky='nsew')
btn9.grid(row=1, column=3, sticky='nsew')
btn8.grid(row=1, column=2, sticky='nsew')
btn7.grid(row=1, column=1, sticky='nsew')
btn.grid(row=2, column=5, sticky='nsew')
btnz.grid(row=3, column=5, sticky='nsew')
btn6.grid(row=2, column=3, sticky='nsew')
btn5.grid(row=2, column=2, sticky='nsew')
btn4.grid(row=2, column=1, sticky='nsew')
btnm.grid(row=3, column=4, sticky='nsew')
btn3.grid(row=3, column=3, sticky='nsew')
btn2.grid(row=3, column=2, sticky='nsew')
btn1.grid(row=3, column=1, sticky='nsew')
btn0.grid(row=4, column=1, sticky='nsew')
btn000.grid(row=4, column=2, columnspan=2, sticky='nsew')

mainloop()